### ISSUE TITLE
Bot attempting to send multiple lines sends message

### ISSUE THREAD

**Issue by ghost** [jediknight813/llama-cpp-discord-bot#1]
Hello, when thw bot attwmpts to send multiple line responses it triggers the message sending only the first line.
So if the bot is trying to send:
"Hello my name is mike
How are you?"
Starting the secondnline triggwrs the message and all we get is:
"Hello my name is mike."
I think it's the bot crearing a newline is being interuppted as an enter press.

**Comment by jediknight813** [comment]
Fixed it, by default it was stopping text generation on a newline.
