### ISSUE TITLE
possible to make it use GPUs?

### ISSUE THREAD

**Issue by AmFerra** [jediknight813/llama-cpp-discord-bot#10]
is it possible to make it use GPU instead of CPU?
it might already be possible, and I dont see it, or dont know how.

**Comment by jediknight813** [comment]
It is possible, I'll have to make a new Dockerfile for it though, I'll look into it.

**Comment by jediknight813** [comment]
Added a gpu Dockerfile, try it out, make sure to set the number of gpu layers in the settings.py file.

**Comment by AmFerra** [comment]
Alright, thanks. Also, is there a way to adjust the temperature of the responses? I dont see any way.
