### ISSUE TITLE
Unsufficient driver version for cuda runtime

### ISSUE THREAD

**Issue by AmFerra** [jediknight813/llama-cpp-discord-bot#11]
using GPU version
CUDA error 35 at /tmp/........../ggml-cuda.cu:481: CUDA driver version is insufficient for CUDA runtime version.
it has a GTX 950

**Comment by jediknight813** [comment]
https://gist.github.com/standaloneSA/99788f30466516dbcc00338b36ad5acf

Your card isn't supported by the latest CUDA version.

ARG CUDA_IMAGE="12.1.1-devel-ubuntu22.04" You need to change this in the Dockerfile.gpu to the correct version for your card.
