### ISSUE TITLE
[Question] Passing paramaters and memory

### ISSUE THREAD

**Issue by ghost** [jediknight813/llama-cpp-discord-bot#2]
Is it possible to pass items like ctx_size and repeat_penalty to the bot?

And also is it possible to implemtn some form of memory?

Thank you!

**Comment by jediknight813** [comment]
I added repeat_penalty to bot, you can set it the settings.py file, and what kind of memory? long term or just the past few messages in the channel?

**Comment by ghost** [comment]
Thank you, and yeah I was thinking long term, but I figure just a few messages would do.

Also is it okay if i work on porting from settings.py to a .env file?

**Comment by jediknight813** [comment]
Added chat history, you can configure it in the settings.py file, what would be the advantages of moving to an .env?

**Comment by ghost** [comment]
Thank you thank you!

The thing with the settings.py is that needs to be stashed each time if the file is updated.

If settujgs were stored in .env file then settings.py could be edited as many times as need without user changes being affected.

I was thinking of making a  .env.example file the user would copy and edit
