### ISSUE TITLE
bot_memories file doesnt change when personality is changed via /change_bot_personality command

### ISSUE THREAD

**Issue by ghost** [jediknight813/llama-cpp-discord-bot#5]
When the /change_bot_personality command is run the accompanying bot_memories's json is not

**Comment by jediknight813** [comment]
![Screen Shot 2023-05-23 at 4 14 56 PM](https://github.com/jediknight813/llama-cpp-discord-bot/assets/17935336/a17a7bde-ad47-405c-9c03-008fc2a5b716)

did you put it in like this?

**Comment by jediknight813** [comment]
Figured it out, it should be working correctly now.
